---
- hosts: all
  gather_facts: true
  vars_files: variables.yml
        
  tasks:

    - name: Create directory structure
      win_file:
        path: C:\Temp\{{ item }}\
        state: directory
      loop: "{{ my_list | selectattr('name', 'equalto', inventory_hostname) | map(attribute='command') | first }}"
      
    - name: Debug ansible hostname
      debug:
        msg: "{{ ansible_hostname }}"

    - name: Debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }}"
