---
- hosts: all
  gather_facts: true
  vars:
    my_list:
      - name: Item 1
        command:
          - 100
          - 101
      - name: Item 2
        command:
          - 200
          - 201
      - name: Item 3
        command:
          - 300
          - 301
        
  tasks:

    - name: Display the looked-up value
      win_shell: "{{ item }}"
      loop: "{{ my_list | selectattr('name', 'equalto', 'Item 2') | map(attribute='command') | list }}"

    - name: Debug ansible hostname
      debug:
        msg: "{{ ansible_hostname }}"

    - name: Debug inventory hostname
      debug:
        msg: "{{ inventory_hostname }}"
