---
- hosts: localhost
  gather_facts: false
  vars:
    my_list:
      - name: Item 1
        value: 100
      - name: Item 2
        value: 200
      - name: Item 3
        value: 300
        
  tasks:

    - name: Display the looked-up value
      debug:
        msg: "{{ my_list | selectattr('name', 'equalto', 'Item 2') | map(attribute='value') | list | first }}"

    - name: Debug
      debug:
        msg: "{{ ansible_hostname }}"
